#!/usr/bin/env python3
"""Puzzle generator for The Sunday Topol.

Builds 100 easy (15x15) and 100 medium (21x21) freeform crosswords from
curated word/clue banks, verifies every grid (interlocking crossings,
single connected component, clue/grid consistency), and writes puzzles.js.

Run:  python3 generate-puzzles.py
"""
import json
import random
import sys

# ---------------------------------------------------------------------------
# EASY bank — general knowledge for an American adult. Straightforward clues:
# household names, geography, food, TV, sports, everyday vocabulary.
# ---------------------------------------------------------------------------
EASY = [
    ("OPRAH", "Talk show legend Winfrey"),
    ("ELVIS", "The King of Rock and Roll"),
    ("DOLLY", "Parton of 'Jolene' fame"),
    ("SINATRA", "Ol' Blue Eyes"),
    ("BEATLES", "Fab Four from Liverpool"),
    ("MADONNA", "'Material Girl' singer"),
    ("DISNEY", "Walt of Mickey Mouse fame"),
    ("PIXAR", "Studio behind 'Toy Story'"),
    ("JAWS", "1975 shark blockbuster"),
    ("ROCKY", "Boxer played by Stallone"),
    ("YODA", "Little green Jedi master"),
    ("VADER", "Darth of 'Star Wars'"),
    ("OSCAR", "Gold statuette handed out in Hollywood"),
    ("EMMY", "TV's top award"),
    ("GRAMMY", "Music's top award"),
    ("SITCOM", "'Friends' or 'Seinfeld,' e.g."),
    ("RERUN", "Episode you've seen before"),
    ("JEOPARDY", "Quiz show with answers first"),
    ("WHEEL", "'___ of Fortune'"),
    ("PIANO", "Instrument with 88 keys"),
    ("GUITAR", "Instrument with frets and strings"),
    ("BANJO", "Bluegrass strummer"),
    ("DRUM", "Instrument in a marching band's beat section"),
    ("CHOIR", "Church singing group"),
    ("OPERA", "Show with arias"),
    ("STAGE", "Where actors perform"),
    ("TICKET", "Admission slip"),
    ("USHER", "One who shows you to your seat"),
    ("POPCORN", "Movie theater snack"),
    ("SODA", "Pop, in the Midwest"),
    ("PIZZA", "Pepperoni pie"),
    ("TACO", "Tuesday's dinner, to some"),
    ("BURGER", "Grilled patty on a bun"),
    ("HOTDOG", "Ballpark frank"),
    ("KETCHUP", "Fries' red partner"),
    ("MUSTARD", "Yellow hot dog topper"),
    ("PICKLE", "Dill spear"),
    ("BACON", "Breakfast strips"),
    ("WAFFLE", "Breakfast item with a grid"),
    ("PANCAKE", "Flapjack"),
    ("SYRUP", "Maple pancake topper"),
    ("OMELET", "Folded egg dish"),
    ("BAGEL", "Roll with a hole"),
    ("DONUT", "Cop-show cliché pastry"),
    ("MUFFIN", "Blueberry bakery item"),
    ("TOAST", "Browned bread, or a champagne salute"),
    ("BUTTER", "Toast spread"),
    ("CHEESE", "Say it for the camera"),
    ("SALAD", "Caesar or Cobb"),
    ("STEAK", "Ribeye or sirloin"),
    ("LOBSTER", "Maine delicacy with claws"),
    ("SHRIMP", "Cocktail seafood"),
    ("TUNA", "Common sandwich fish"),
    ("SALMON", "Fish that swims upstream"),
    ("PASTA", "Spaghetti or penne"),
    ("NOODLE", "Ramen strand"),
    ("GARLIC", "Vampire repellent in the kitchen"),
    ("ONION", "Vegetable that brings tears"),
    ("PEPPER", "Salt's tablemate"),
    ("OLIVE", "Martini garnish"),
    ("LEMON", "Sour fruit, or a bad used car"),
    ("LIME", "Margarita fruit"),
    ("PEACH", "Georgia's fruit"),
    ("APPLE", "Big ___ (New York City)"),
    ("BANANA", "Fruit with a peel"),
    ("GRAPE", "Wine fruit"),
    ("MELON", "Cantaloupe, for one"),
    ("CHERRY", "Sundae topper"),
    ("PECAN", "Southern pie nut"),
    ("PEANUT", "Ballpark shell snack"),
    ("PRETZEL", "Twisted stadium snack"),
    ("NACHO", "Chip topped with cheese"),
    ("SALSA", "Chip dip, or a dance"),
    ("QUESO", "Cheese, in Spanish"),
    ("BURRITO", "Overstuffed Tex-Mex wrap"),
    ("COOKIE", "Chocolate chip treat"),
    ("BROWNIE", "Fudgy square"),
    ("SUNDAE", "Ice cream with toppings"),
    ("VANILLA", "Plain ice cream flavor"),
    ("FUDGE", "Rich chocolate candy"),
    ("CANDY", "Halloween haul"),
    ("SUGAR", "Sweet tooth's craving"),
    ("HONEY", "Bee product, or a term of endearment"),
    ("COFFEE", "Morning cup of joe"),
    ("LATTE", "Espresso with steamed milk"),
    ("DECAF", "Coffee without the buzz"),
    ("COCOA", "Hot winter drink"),
    ("CIDER", "Fall apple drink"),
    ("TEXAS", "The Lone Star State"),
    ("IDAHO", "Famous potato state"),
    ("IOWA", "State with the first caucuses"),
    ("OHIO", "Buckeye State"),
    ("UTAH", "Beehive State"),
    ("MAINE", "Easternmost U.S. state"),
    ("ALASKA", "Largest U.S. state"),
    ("HAWAII", "Aloha State"),
    ("FLORIDA", "Sunshine State"),
    ("NEVADA", "Silver State with Las Vegas"),
    ("KANSAS", "Dorothy's home state"),
    ("VEGAS", "Sin City, for short"),
    ("MIAMI", "South Beach city"),
    ("BOSTON", "Red Sox city"),
    ("DALLAS", "Cowboys' Texas city"),
    ("DENVER", "Mile High City"),
    ("SEATTLE", "Space Needle city"),
    ("CHICAGO", "The Windy City"),
    ("MEMPHIS", "Graceland's city"),
    ("ATLANTA", "Peach State capital"),
    ("ORLANDO", "Disney World's city"),
    ("TULSA", "Oklahoma's second city"),
    ("RENO", "'Biggest Little City in the World'"),
    ("CANADA", "Neighbor to the north"),
    ("MEXICO", "Neighbor to the south"),
    ("PARIS", "Eiffel Tower city"),
    ("LONDON", "Big Ben's city"),
    ("ROME", "Colosseum city"),
    ("EGYPT", "Pyramid land"),
    ("HOLLAND", "Tulip and windmill land"),
    ("BRAZIL", "Carnival country"),
    ("HHmm", "placeholder"),
    ("SPAIN", "Flamenco country"),
    ("ITALY", "Boot-shaped country"),
    ("IRELAND", "Emerald Isle"),
    ("OCEAN", "The Atlantic or Pacific"),
    ("BEACH", "Spring break destination"),
    ("ISLAND", "Land surrounded by water"),
    ("RIVER", "The Mississippi, e.g."),
    ("CANYON", "The Grand ___"),
    ("PRAIRIE", "Great Plains grassland"),
    ("VALLEY", "Low land between hills"),
    ("SUMMIT", "Mountain top"),
    ("TRAIL", "Hiker's path"),
    ("CAMP", "Pitch a tent site"),
    ("CABIN", "Rustic woods getaway"),
    ("MOTEL", "Roadside lodging"),
    ("DINER", "Roadside eatery with a counter"),
    ("ROUTE", "Historic ___ 66"),
    ("SUBWAY", "Underground train, or a sandwich chain"),
    ("AMTRAK", "U.S. passenger railroad"),
    ("SEDAN", "Four-door car"),
    ("PICKUP", "Truck with a bed"),
    ("GARAGE", "Where the car sleeps"),
    ("ENGINE", "It's under the hood"),
    ("BRAKE", "Pedal next to the gas"),
    ("HORN", "It honks"),
    ("TIRE", "It might go flat"),
    ("DETOUR", "Alternate route"),
    ("TRAFFIC", "Rush hour headache"),
    ("YIELD", "Triangular road sign"),
    ("LIMO", "Prom night ride, for short"),
    ("TAXI", "Yellow cab"),
    ("PILOT", "One in the cockpit"),
    ("RUNWAY", "Where planes take off"),
    ("LUGGAGE", "Carousel items at the airport"),
    ("TOURIST", "Camera-toting traveler"),
    ("YANKEES", "Bronx Bombers"),
    ("METS", "Queens baseball team"),
    ("CUBS", "Wrigley Field team"),
    ("LAKERS", "L.A. basketball team"),
    ("SOCCER", "Football, to the rest of the world"),
    ("TENNIS", "Sport with love and aces"),
    ("BOWLING", "Sport with strikes and spares"),
    ("GOLF", "Sport with a 19th hole"),
    ("CADDY", "Golfer's bag carrier"),
    ("PUTTER", "Green club"),
    ("BOGEY", "One over par"),
    ("EAGLE", "Two under par, or a bald bird"),
    ("HOMER", "Round-tripper, or a Simpson"),
    ("INNING", "One ninth of a ballgame"),
    ("UMPIRE", "'Strike three!' caller"),
    ("COACH", "Team leader with a whistle"),
    ("HUDDLE", "Football strategy circle"),
    ("TOUCHDOWN", "Six-pointer on the gridiron"),
    ("KICKOFF", "Football game starter"),
    ("REFEREE", "Zebra-striped official"),
    ("JERSEY", "Player's numbered shirt"),
    ("STADIUM", "Where the home team plays"),
    ("TROPHY", "Winner's hardware"),
    ("MEDAL", "Olympic prize"),
    ("RELAY", "Race with a baton"),
    ("SPRINT", "All-out dash"),
    ("MARATHON", "26.2-mile run"),
    ("YOGA", "Practice with downward dog"),
    ("TREADMILL", "Gym machine for runners"),
    ("DUMBBELL", "Hand weight"),
    ("POKER", "Game with bluffs and chips"),
    ("BINGO", "Game hall shout"),
    ("CHESS", "Game with a checkered board"),
    ("CHECKERS", "Game of kings and jumps"),
    ("DOMINO", "Dotted game tile"),
    ("PUZZLE", "What you're solving right now"),
    ("RIDDLE", "Brain teaser"),
    ("CHARADES", "Party game of acting out"),
    ("MONOPOLY", "Board game with Boardwalk"),
    ("SCRABBLE", "Board game with letter tiles"),
    ("DOCTOR", "One with an M.D."),
    ("LAWYER", "One who passed the bar"),
    ("JUDGE", "Gavel wielder"),
    ("JURY", "Twelve in a courtroom box"),
    ("SHERIFF", "County lawman with a star"),
    ("MAYOR", "City hall boss"),
    ("SENATOR", "One of 100 in D.C."),
    ("BALLOT", "Election day paper"),
    ("BANKER", "Loan approver"),
    ("TELLER", "Bank window worker"),
    ("CASHIER", "Checkout worker"),
    ("WAITER", "One who takes your order"),
    ("BARBER", "Shop with a striped pole"),
    ("TAILOR", "One who hems and alters"),
    ("PLUMBER", "Leaky faucet fixer"),
    ("JANITOR", "School custodian"),
    ("FARMER", "One with acres and a tractor"),
    ("RANCHER", "Cattle spread owner"),
    ("NANNY", "Hired childminder"),
    ("REALTOR", "House-selling agent"),
    ("EDITOR", "Newspaper desk boss"),
    ("AUTHOR", "Book writer"),
    ("POET", "Sonnet writer"),
    ("NOVEL", "Fiction shelf item"),
    ("MEMOIR", "Life story, written by its liver"),
    ("LIBRARY", "Quiet book building"),
    ("CHAPTER", "Book division"),
    ("COMICS", "Sunday funnies"),
    ("HEADLINE", "Front page grabber"),
    ("GOSSIP", "Juicy talk"),
    ("RUMOR", "Unverified story"),
    ("SECRET", "It's kept under wraps"),
    ("WHISPER", "Library-volume speech"),
    ("SHOUT", "Opposite of a whisper"),
    ("APPLAUSE", "Sound after a great show"),
    ("ENCORE", "'One more song!'"),
    ("DOLLAR", "George Washington bill"),
    ("NICKEL", "Five-cent coin"),
    ("PENNY", "Lincoln coin"),
    ("QUARTER", "Coin for a parking meter"),
    ("WALLET", "Billfold"),
    ("BUDGET", "Spending plan"),
    ("COUPON", "Clip-out saver"),
    ("BARGAIN", "Great deal"),
    ("AUCTION", "Going, going, gone event"),
    ("RECEIPT", "Proof of purchase"),
    ("REFUND", "Money back"),
    ("SAVINGS", "Rainy-day account"),
    ("PAYDAY", "When the check arrives"),
    ("TIP", "Server's bonus"),
    ("TAX", "April 15 concern"),
    ("LEASE", "Renter's contract"),
    ("PORCH", "Rocking chair spot"),
    ("ATTIC", "Top-floor storage"),
    ("CELLAR", "Below-ground storage"),
    ("CLOSET", "Where skeletons hide, idiomatically"),
    ("KITCHEN", "Where the magic happens at Thanksgiving"),
    ("PANTRY", "Canned goods closet"),
    ("HALLWAY", "Corridor between rooms"),
    ("DRIVEWAY", "Where the car is parked at home"),
    ("MAILBOX", "Letter receptacle at the curb"),
    ("DOORBELL", "Visitor announcer"),
    ("WELCOME", "Mat greeting"),
    ("CURTAIN", "Window cover"),
    ("CARPET", "Wall-to-wall floor cover"),
    ("SOFA", "Living room couch"),
    ("RECLINER", "Dad's favorite chair"),
    ("PILLOW", "Head rest"),
    ("BLANKET", "Bed cover"),
    ("QUILT", "Patchwork bed cover"),
    ("DRESSER", "Bedroom drawers"),
    ("MIRROR", "Reflection giver"),
    ("FAUCET", "Sink fixture"),
    ("SHOWER", "Morning rinse"),
    ("TOWEL", "Post-shower wrap"),
    ("RAZOR", "Shaving tool"),
    ("LOTION", "Dry skin soother"),
    ("PERFUME", "Fragrance counter buy"),
    ("LAUNDRY", "Hamper contents"),
    ("HANGER", "Closet triangle"),
    ("IRON", "Wrinkle remover"),
    ("VACUUM", "Carpet cleaner"),
    ("BROOM", "Sweeper"),
    ("MOP", "Wet-floor cleaner"),
    ("BUCKET", "Mop's partner"),
    ("SPONGE", "Dish scrubber"),
    ("TRASH", "Garbage"),
    ("RECYCLE", "Put in the blue bin"),
    ("GADGET", "Handy little device"),
    ("REMOTE", "Couch potato's scepter"),
    ("CHANNEL", "What a remote changes"),
    ("VOLUME", "Remote's up/down setting"),
    ("SCREEN", "TV or phone surface"),
    ("CHARGER", "Phone's lifeline"),
    ("SELFIE", "Arm's-length photo"),
    ("EMAIL", "Inbox filler"),
    ("PASSWORD", "Login secret"),
    ("WEBSITE", "Online destination"),
    ("PRINTER", "Office machine that jams"),
    ("STAPLER", "Desk fastener"),
    ("FOLDER", "File holder"),
    ("MEMO", "Office note"),
    ("MEETING", "Calendar time-eater"),
    ("DEADLINE", "Due date"),
    ("RESUME", "Job seeker's summary"),
    ("SALARY", "Annual pay"),
    ("OFFICE", "Cubicle setting, or a Steve Carell show"),
    ("BREAK", "Coffee ___"),
    ("WEEKEND", "Saturday and Sunday"),
    ("HOLIDAY", "Day off on the calendar"),
    ("SUMMER", "Season of barbecues"),
    ("AUTUMN", "Season of falling leaves"),
    ("WINTER", "Season of snow shovels"),
    ("SPRING", "Season of cleaning, supposedly"),
    ("AUGUST", "Month with no U.S. holidays"),
    ("OCTOBER", "Pumpkin spice month"),
    ("FRIDAY", "TGIF day"),
    ("MONDAY", "Garfield's least favorite day"),
    ("NOON", "High ___ (12 p.m.)"),
    ("MIDNIGHT", "When the ball drops"),
    ("SUNRISE", "Early bird's reward"),
    ("SUNSET", "Golden hour event"),
    ("RAINBOW", "After-storm arc"),
    ("THUNDER", "Lightning's soundtrack"),
    ("BREEZE", "Gentle wind"),
    ("FROST", "Windshield scraping cause"),
    ("SNOWMAN", "Carrot-nosed yard figure"),
    ("SLED", "Snow day ride"),
    ("MITTEN", "Thumb-only hand warmer"),
    ("SCARF", "Winter neck wrap"),
    ("PARKA", "Heavy winter coat"),
    ("UMBRELLA", "Rainy day carry"),
    ("PUDDLE", "What kids splash in"),
    ("GARDEN", "Where tomatoes grow at home"),
    ("SHOVEL", "Digging tool"),
    ("RAKE", "Leaf gatherer"),
    ("HOSE", "Garden waterer"),
    ("WEED", "Unwanted garden guest"),
    ("DAISY", "'He loves me' flower"),
    ("TULIP", "Spring bulb bloom"),
    ("CACTUS", "Prickly desert plant"),
    ("ACORN", "Squirrel's stash item"),
    ("MAPLE", "Syrup tree"),
    ("WILLOW", "Weeping tree"),
    ("MEADOW", "Wildflower field"),
    ("ROBIN", "Red-breasted spring bird"),
    ("SPARROW", "Common little brown bird"),
    ("PIGEON", "City park bird"),
    ("PARROT", "Bird that talks back"),
    ("TURKEY", "Thanksgiving bird"),
    ("ROOSTER", "Farm's alarm clock"),
    ("PONY", "Small horse"),
    ("KITTEN", "Baby cat"),
    ("PUPPY", "Baby dog"),
    ("BEAGLE", "Snoopy's breed"),
    ("POODLE", "Fancy-cut dog breed"),
    ("COLLIE", "Lassie's breed"),
    ("HAMSTER", "Wheel-running pet"),
    ("GOLDFISH", "Bowl dweller"),
    ("TURTLE", "Slow shelled pet"),
    ("RABBIT", "Carrot cruncher"),
    ("SQUIRREL", "Backyard nut hoarder"),
    ("SKUNK", "Striped stinker"),
    ("MOOSE", "Antlered giant of the north woods"),
    ("BISON", "American plains beast"),
    ("COYOTE", "Roadrunner's cartoon rival"),
    ("DOLPHIN", "Flipper, for one"),
    ("PANDA", "Bamboo-munching bear"),
    ("KOALA", "Aussie tree hugger"),
    ("MONKEY", "Barrel of laughs animal"),
    ("GIRAFFE", "Long-necked zoo star"),
    ("HIPPO", "River heavyweight, briefly"),
    ("RHINO", "Horned heavyweight, briefly"),
    ("CIRCUS", "Big top show"),
    ("JUGGLER", "One keeping balls in the air"),
    ("PARADE", "Macy's Thanksgiving event"),
    ("FLOAT", "Parade platform, or root beer treat"),
    ("CARNIVAL", "Midway and rides event"),
    ("FERRIS", "___ wheel"),
    ("ARCADE", "Quarter-eating game room"),
    ("PINBALL", "Flipper game"),
    ("JACKPOT", "Slot machine dream"),
    ("LOTTERY", "Powerball, e.g."),
    ("BIRTHDAY", "Cake-and-candles occasion"),
    ("BALLOON", "Party floater"),
    ("CONFETTI", "New Year's Eve shower"),
    ("RIBBON", "Gift wrap curl"),
    ("INVITE", "Party summons, casually"),
    ("WEDDING", "Aisle event"),
    ("GROOM", "Tuxedoed half of a wedding"),
    ("BOUQUET", "What the bride tosses"),
    ("HONEYMOON", "Post-wedding getaway"),
    ("ANNIVERSARY", "Yearly couple's milestone"),
    ("COUSIN", "Aunt's kid"),
    ("NEPHEW", "Sibling's son"),
    ("GRANDMA", "Nana"),
    ("GRANDPA", "Pop-pop"),
    ("TODDLER", "Terrible-twos kid"),
    ("TEENAGER", "Eye-rolling family member"),
    ("CURFEW", "Teen's deadline"),
    ("ALLOWANCE", "Kid's weekly cash"),
    ("CHORE", "Dish duty, e.g."),
    ("HOMEWORK", "After-school assignment"),
    ("RECESS", "Playground break"),
    ("TEACHER", "One with a red pen"),
    ("PENCIL", "No. 2 writing tool"),
    ("ERASER", "Mistake fixer"),
    ("CRAYON", "Kid's coloring stick"),
    ("GLUE", "Craft table stickum"),
    ("SCISSORS", "Rock's paper-cutting rival"),
    ("BACKPACK", "Student's carryall"),
    ("LOCKER", "Hallway storage at school"),
    ("DIPLOMA", "Graduation scroll"),
    ("COLLEGE", "Campus institution"),
    ("FRESHMAN", "First-year student"),
    ("PROM", "Spring formal dance"),
    ("REUNION", "Class gathering years later"),
    ("SMILE", "Camera request"),
    ("LAUGHTER", "The best medicine, they say"),
    ("GIGGLE", "Little laugh"),
    ("HICCUP", "Involuntary 'hic'"),
    ("SNEEZE", "'Gesundheit' trigger"),
    ("YAWN", "Contagious sleepy signal"),
    ("NAP", "Afternoon snooze"),
    ("SNORE", "Sleeper's sound effect"),
    ("DREAM", "REM-stage story"),
    ("ALARM", "Morning buzzer"),
    ("SLIPPER", "Cozy house shoe"),
    ("PAJAMAS", "Bedtime outfit"),
    ("ROBE", "Post-shower cover-up"),
    ("SNEAKER", "Gym shoe"),
    ("SANDAL", "Open-toed summer shoe"),
    ("LOAFER", "Slip-on shoe"),
    ("TUXEDO", "Black-tie attire"),
    ("NECKTIE", "Father's Day cliché gift"),
    ("BUTTON", "Shirt fastener"),
    ("ZIPPER", "Toothy fastener"),
    ("POCKET", "Where keys hide"),
    ("DENIM", "Jeans fabric"),
    ("FLANNEL", "Lumberjack shirt fabric"),
    ("SWEATER", "Ugly holiday garment, sometimes"),
    ("EARRING", "Lobe decoration"),
    ("NECKLACE", "Pendant's place"),
    ("DIAMOND", "April birthstone, or a ball field"),
    ("EMERALD", "Green gem"),
    ("PEARL", "Oyster's prize"),
    ("HEIRLOOM", "Passed-down treasure"),
    ("ANTIQUE", "Roadshow appraisal item"),
    ("BARGAIN2", "placeholder"),
    ("HERO", "Cape wearer, or a big sandwich"),
    ("VILLAIN", "Story's bad guy"),
    ("WIZARD", "Oz title figure"),
    ("GENIE", "Lamp dweller granting wishes"),
    ("MERMAID", "Ariel, for one"),
    ("PIRATE", "Walk-the-plank type"),
    ("COWBOY", "Rodeo rider"),
    ("SADDLE", "Rider's seat"),
    ("LASSO", "Cowboy's loop"),
    ("RODEO", "Bronco-busting event"),
    ("RANCH", "Cattle spread, or a salad dressing"),
    ("CANOE", "Paddled boat"),
    ("KAYAK", "Boat that's a palindrome"),
    ("ANCHOR", "It keeps a boat put, or reads the news"),
    ("HARBOR", "Boat haven"),
    ("SEAGULL", "Boardwalk fry thief"),
    ("SANDCASTLE", "Beach construction project"),
    ("SEASHELL", "'She sells' beach item"),
    ("SURF", "Ride the waves"),
    ("TIDE", "It comes in and goes out"),
    ("CRUISE", "Buffet-heavy vacation at sea"),
    ("RESORT", "All-inclusive getaway spot"),
    ("SOUVENIR", "Vacation keepsake"),
    ("POSTCARD", "'Wish you were here' mailer"),
    ("PASSPORT", "International travel booklet"),
    ("COMPASS", "It points north"),
    ("LANTERN", "Camping light"),
    ("CAMPFIRE", "S'mores heat source"),
    ("MARSHMALLOW", "S'mores puff"),
    ("PICNIC", "Basket-and-blanket meal"),
    ("BARBECUE", "Backyard grill-out"),
    ("APRON", "Grill master's wear"),
    ("SPATULA", "Burger flipper"),
    ("SKILLET", "Frying pan"),
    ("KETTLE", "Whistling water heater"),
    ("BLENDER", "Smoothie maker"),
    ("TOASTER", "It pops up breakfast"),
    ("RECIPE", "Cook's instructions"),
    ("LEFTOVERS", "Tomorrow's lunch from tonight's dinner"),
    ("POTLUCK", "Bring-a-dish gathering"),
    ("CASSEROLE", "Church supper dish"),
    ("GRAVY", "Thanksgiving pour"),
    ("STUFFING", "Turkey's sidekick"),
    ("PUMPKIN", "Jack-o'-lantern base"),
    ("COSTUME", "October 31 outfit"),
    ("HAUNTED", "Like some Halloween houses"),
    ("GHOST", "Sheet-wearing spook"),
    ("WITCH", "Broomstick flier"),
    ("MISTLETOE", "Kissing plant of December"),
    ("REINDEER", "Sleigh puller"),
    ("SLEIGH", "Santa's ride"),
    ("CHIMNEY", "Santa's entrance"),
    ("STOCKING", "Mantel hanging"),
    ("EGGNOG", "Rich holiday drink"),
    ("FIREWORKS", "Fourth of July display"),
    ("LIBERTY", "Statue of ___"),
    ("FLAG", "Stars and Stripes"),
    ("ANTHEM", "'The Star-Spangled Banner,' e.g."),
    ("CAPITOL", "Domed D.C. building"),
    ("LINCOLN", "President on the penny"),
    ("GEORGE", "First president's first name"),
    ("EAGLE2", "placeholder"),
    ("UNCLE", "___ Sam"),
    ("PATRIOT", "Flag-waving type, or a New England player"),
    ("VETERAN", "November 11 honoree"),
    ("PARADE2", "placeholder"),
    ("MUSEUM", "Field trip destination"),
    ("STATUE", "Park pedestal topper"),
    ("FOUNTAIN", "Coin-toss pool"),
    ("BENCH", "Park seat"),
    ("SIDEWALK", "Where hopscotch happens"),
    ("CROSSWALK", "Striped street crossing"),
    ("CORNER", "Where two streets meet"),
    ("AVENUE", "Fifth ___, famed shopping street"),
    ("SKYLINE", "City silhouette"),
    ("ELEVATOR", "Otis invention"),
    ("LOBBY", "Hotel entrance area"),
    ("PENTHOUSE", "Top-floor luxury unit"),
    ("BALCONY", "Romeo and Juliet's spot"),
    ("NEIGHBOR", "One next door"),
    ("FENCE", "Property line marker"),
    ("GOSSIP2", "placeholder"),
    ("SSN", "placeholder-skip"),
]

# ---------------------------------------------------------------------------
# MEDIUM bank — trickier vocabulary, world knowledge, oblique clues,
# plus long entries to span the 21x21 grid.
# ---------------------------------------------------------------------------
MEDIUM = [
    ("MISSISSIPPI", "River with four S's in its name"),
    ("CONSTELLATION", "Orion or Cassiopeia"),
    ("KALEIDOSCOPE", "Tube of tumbling colors"),
    ("ENCYCLOPEDIA", "Britannica, notably"),
    ("REFRIGERATOR", "Magnet-covered kitchen giant"),
    ("THUNDERSTORM", "Summer boomer"),
    ("PHILADELPHIA", "City of Brotherly Love"),
    ("ROLLERCOASTER", "Ride with loops, or a turbulent stretch"),
    ("BUTTERSCOTCH", "Golden candy flavor"),
    ("HUMMINGBIRD", "Bird that can hover and fly backward"),
    ("POMEGRANATE", "Fruit of many seeds in Greek myth"),
    ("CALLIGRAPHY", "Elegant penmanship"),
    ("ARCHIPELAGO", "Island chain"),
    ("PLANETARIUM", "Dome of projected stars"),
    ("TRAMPOLINE", "Backyard bouncer"),
    ("YELLOWSTONE", "First U.S. national park"),
    ("ALBUQUERQUE", "New Mexico's largest city"),
    ("METAMORPHOSIS", "Caterpillar-to-butterfly change, or a Kafka tale"),
    ("MASQUERADE", "Ball where identities hide"),
    ("SILHOUETTE", "Backlit outline"),
    ("EQUILIBRIUM", "State of balance"),
    ("CATASTROPHE", "Utter disaster"),
    ("HYPOTHESIS", "Scientist's testable hunch"),
    ("PHENOMENON", "Observable marvel"),
    ("PARLIAMENT", "Britain's legislature, or a group of owls"),
    ("AMBASSADOR", "Embassy's top diplomat"),
    ("FILIBUSTER", "Senate stalling tactic"),
    ("GERRYMANDER", "Redraw districts for advantage"),
    ("RENAISSANCE", "Da Vinci's era"),
    ("GUILLOTINE", "French Revolution device"),
    ("HIEROGLYPH", "Symbol on an Egyptian wall"),
    ("SARCOPHAGUS", "Stone coffin"),
    ("ACROPOLIS", "Athens' high city"),
    ("COLOSSEUM", "Arena the gladiators knew"),
    ("AQUEDUCT", "Roman water carrier"),
    ("CATACOMBS", "Underground burial maze"),
    ("STONEHENGE", "Salisbury Plain mystery"),
    ("GONDOLIER", "Venetian boat pilot"),
    ("MATADOR", "Cape-waving bullfighter"),
    ("FLAMENCO", "Fiery Spanish dance"),
    ("CASTANETS", "Clicking dance accessories"),
    ("BAGPIPES", "Highland droners"),
    ("ACCORDION", "Polka squeezebox"),
    ("HARPSICHORD", "Baroque keyboard"),
    ("XYLOPHONE", "Mallet-struck bars"),
    ("SAXOPHONE", "Coltrane's instrument"),
    ("CLARINET", "Benny Goodman's licorice stick"),
    ("CONCERTO", "Soloist-plus-orchestra work"),
    ("CRESCENDO", "Gradual musical swell"),
    ("FALSETTO", "Bee Gees vocal register"),
    ("ACAPPELLA", "Sung without instruments"),
    ("SERENADE", "Song beneath a window"),
    ("LULLABY", "Cradle song"),
    ("OVERTURE", "Opera's opening"),
    ("LIBRETTO", "Opera's text"),
    ("MAESTRO", "Baton wielder"),
    ("VIRTUOSO", "Dazzling performer"),
    ("PRODIGY", "Mozart at age five, e.g."),
    ("REPERTOIRE", "Performer's stock of pieces"),
    ("CHOREOGRAPHY", "Dance design"),
    ("PIROUETTE", "Ballet spin"),
    ("MATINEE", "Afternoon performance"),
    ("INTERMISSION", "Theater's halftime"),
    ("UNDERSTUDY", "Actor's just-in-case double"),
    ("MONOLOGUE", "Solo speech"),
    ("SOLILOQUY", "Hamlet's 'To be or not to be,' e.g."),
    ("PLAYWRIGHT", "Drama's author"),
    ("PROTAGONIST", "Story's central figure"),
    ("ANTAGONIST", "Protagonist's foil"),
    ("NARRATOR", "Story's telling voice"),
    ("EPILOGUE", "After-the-end chapter"),
    ("ANTHOLOGY", "Collection of works"),
    ("MANUSCRIPT", "Author's submission"),
    ("PSEUDONYM", "Mark Twain, to Samuel Clemens"),
    ("METAPHOR", "'All the world's a stage,' e.g."),
    ("HYPERBOLE", "Exaggeration for effect"),
    ("ALLITERATION", "Peter Piper's device"),
    ("ONOMATOPOEIA", "'Buzz' or 'hiss,' linguistically"),
    ("PALINDROME", "'Racecar,' for one"),
    ("ANAGRAM", "'Listen' vis-à-vis 'silent'"),
    ("ACRONYM", "SCUBA or NASA"),
    ("THESAURUS", "Synonym seeker's book"),
    ("LEXICON", "A language's word stock"),
    ("VERNACULAR", "Everyday local speech"),
    ("COLLOQUIAL", "Informal, as language"),
    ("ELOQUENT", "Silver-tongued"),
    ("VERBOSE", "Using far too many words"),
    ("SUCCINCT", "Brief and to the point"),
    ("CRYPTIC", "Puzzlingly obscure"),
    ("AMBIGUOUS", "Open to two readings"),
    ("PARADOX", "Self-contradictory truth"),
    ("CONUNDRUM", "Knotty problem"),
    ("QUANDARY", "State of perplexity"),
    ("DILEMMA", "Choice between two evils"),
    ("EPIPHANY", "Sudden flash of insight"),
    ("NOSTALGIA", "Longing for the good old days"),
    ("MELANCHOLY", "Wistful sadness"),
    ("EUPHORIA", "Elation's peak"),
    ("SERENDIPITY", "Happy accident"),
    ("WANDERLUST", "Itch to travel"),
    ("VAGABOND", "Wanderer with no fixed address"),
    ("NOMAD", "Desert wanderer"),
    ("PILGRIMAGE", "Journey to a shrine"),
    ("EXPEDITION", "Shackleton undertaking"),
    ("SAFARI", "Serengeti excursion"),
    ("SHERPA", "Everest guide"),
    ("AVALANCHE", "Mountain's white cascade"),
    ("CREVASSE", "Glacier's deep crack"),
    ("PERMAFROST", "Arctic's frozen ground"),
    ("TUNDRA", "Treeless northern plain"),
    ("FJORD", "Norway's carved inlet"),
    ("GEYSER", "Old Faithful, for one"),
    ("CALDERA", "Collapsed volcano's bowl"),
    ("SEISMOGRAPH", "Quake recorder"),
    ("RICHTER", "Quake scale name"),
    ("EPICENTER", "Quake's ground zero"),
    ("TECTONIC", "Kind of shifting plate"),
    ("EROSION", "Canyon carver over eons"),
    ("SEDIMENT", "River-bottom settlings"),
    ("STALACTITE", "Cave ceiling icicle of stone"),
    ("QUICKSAND", "Adventure movie sinkhole"),
    ("OASIS", "Desert's green surprise"),
    ("MIRAGE", "Desert illusion"),
    ("MONSOON", "Mumbai's rainy season"),
    ("TYPHOON", "Pacific hurricane"),
    ("BAROMETER", "Pressure gauge"),
    ("FAHRENHEIT", "Scale where water boils at 212"),
    ("CELSIUS", "Metric temperature scale"),
    ("EQUINOX", "When day equals night"),
    ("SOLSTICE", "June 21 or December 21"),
    ("PERIHELION", "Orbit's closest point to the sun"),
    ("SUPERNOVA", "Star's spectacular end"),
    ("ASTEROID", "Belt member between Mars and Jupiter"),
    ("OBSERVATORY", "Telescope's home"),
    ("ASTRONOMER", "Galileo, for one"),
    ("COPERNICUS", "He put the sun at the center"),
    ("NEWTON", "Apple-inspired physicist"),
    ("EINSTEIN", "Relativity's father"),
    ("CURIE", "Two-time Nobel-winning Marie"),
    ("DARWIN", "Galápagos naturalist"),
    ("MENDEL", "Pea-plant geneticist monk"),
    ("PASTEUR", "Milk-process namesake"),
    ("TESLA", "Edison's AC rival"),
    ("EDISON", "Menlo Park wizard"),
    ("MORSE", "Code man of dots and dashes"),
    ("TELEGRAPH", "Wire for Morse's code"),
    ("PHONOGRAPH", "Edison's record player"),
    ("DAGUERREOTYPE", "Early photograph"),
    ("ZEPPELIN", "Hindenburg, e.g., or a Led band"),
    ("LOCOMOTIVE", "Train's engine"),
    ("CABOOSE", "Train's tail end"),
    ("TURNPIKE", "Toll road"),
    ("VIADUCT", "Valley-spanning bridge"),
    ("SUSPENSION", "Golden Gate bridge type"),
    ("LIGHTHOUSE", "Keeper's coastal tower"),
    ("PERISCOPE", "Submarine's eye"),
    ("SONAR", "Sub's echo locator"),
    ("NAUTICAL", "Of ships and the sea"),
    ("STARBOARD", "Ship's right"),
    ("MUTINY", "Bounty happening of 1789"),
    ("ARMADA", "Spanish fleet of 1588"),
    ("GALLEON", "Treasure fleet vessel"),
    ("PRIVATEER", "Licensed sea raider"),
    ("BUCCANEER", "Caribbean pirate"),
    ("CUTLASS", "Pirate's blade"),
    ("DOUBLOON", "Spanish gold coin"),
    ("INGOT", "Bar of bullion"),
    ("PROSPECTOR", "Forty-niner panning for gold"),
    ("STAGECOACH", "Wells Fargo conveyance"),
    ("FRONTIER", "Wild West edge"),
    ("HOMESTEAD", "Settler's claim"),
    ("TUMBLEWEED", "Western scene roller"),
    ("SAGEBRUSH", "High desert shrub"),
    ("MUSTANG", "Wild western horse, or a Ford"),
    ("PALOMINO", "Golden horse"),
    ("APPALOOSA", "Spotted horse breed"),
    ("BRONCO", "Rodeo bucker"),
    ("STAMPEDE", "Cattle panic"),
    ("LARIAT", "Cowboy's rope"),
    ("SPURS", "Boot jinglers, or San Antonio's team"),
    ("SSKIP", "placeholder-skip"),
    ("MAVERICK", "Unbranded calf, or an independent type"),
    ("RUSTLER", "Cattle thief"),
    ("VIGILANTE", "Law-taker into own hands"),
    ("POSSE", "Sheriff's search party"),
    ("WANTED", "Word atop an outlaw's poster"),
    ("GALLOWS", "Grim frontier fixture"),
    ("TOMBSTONE", "Arizona town of the O.K. Corral"),
    ("EARP", "Wyatt of Tombstone"),
    ("BILLY", "___ the Kid"),
    ("OUTLAW", "Jesse James, for one"),
    ("HEIST", "Ocean's Eleven job"),
    ("GETAWAY", "Robber's escape"),
    ("RANSOM", "Kidnapper's demand"),
    ("HOSTAGE", "Negotiator's concern"),
    ("INTERROGATE", "Grill under a bright light"),
    ("FORENSICS", "CSI science"),
    ("POLYGRAPH", "Lie detector"),
    ("PERJURY", "Lying under oath"),
    ("ACQUITTAL", "'Not guilty' outcome"),
    ("SUBPOENA", "Court summons"),
    ("AFFIDAVIT", "Sworn written statement"),
    ("PARALEGAL", "Law office aide"),
    ("PROSECUTOR", "The People's lawyer"),
    ("DEFENDANT", "One on trial"),
    ("TESTIMONY", "Witness's account"),
    ("EVIDENCE", "Exhibit A, e.g."),
    ("ALIBI", "'I was at the movies,' maybe"),
    ("MOTIVE", "Detective's 'why'"),
    ("SLEUTH", "Gumshoe"),
    ("INCOGNITO", "Traveling under a false name"),
    ("SURVEILLANCE", "Stakeout activity"),
    ("ESPIONAGE", "Cloak-and-dagger trade"),
    ("DOSSIER", "Spy's file"),
    ("CIPHER", "Coded message"),
    ("ENIGMA", "WWII code machine, or a mystery"),
    ("SABOTEUR", "Deliberate wrecker"),
    ("DEFECTOR", "Cold War side-switcher"),
    ("EMBASSY", "Diplomatic outpost"),
    ("ASYLUM", "Refugee's request"),
    ("TREATY", "Versailles document, e.g."),
    ("ARMISTICE", "Ceasefire of November 1918"),
    ("BLOCKADE", "Naval strangle-hold"),
    ("SIEGE", "Troy endured a ten-year one"),
    ("TROJAN", "Kind of horse that fooled Troy"),
    ("ODYSSEY", "Homer's long way home"),
    ("ILIAD", "Homer's war epic"),
    ("ACHILLES", "Hero with a weak heel"),
    ("MINOTAUR", "Bull-headed maze dweller"),
    ("LABYRINTH", "Minotaur's home"),
    ("PEGASUS", "Winged steed of myth"),
    ("PHOENIX", "Ash-born bird, or Arizona's capital"),
    ("CERBERUS", "Hades' three-headed hound"),
    ("MEDUSA", "Her gaze turned men to stone"),
    ("POSEIDON", "Trident-toting sea god"),
    ("APHRODITE", "Greek goddess of love"),
    ("HERCULES", "Twelve-labor strongman"),
    ("ATLAS", "He shouldered the heavens"),
    ("MIDAS", "King with the golden touch"),
    ("PANDORA", "Her box loosed the world's ills"),
    ("ICARUS", "He flew too close to the sun"),
    ("NARCISSUS", "He fell for his own reflection"),
    ("VALHALLA", "Viking warriors' hall"),
    ("MJOLNIR", "Thor's hammer"),
    ("EXCALIBUR", "Sword from the stone (or the lake)"),
    ("CAMELOT", "Arthur's court"),
    ("MERLIN", "Arthur's wizard"),
    ("GRAIL", "Knights' holy quest object"),
    ("JOUST", "Lance-to-lance contest"),
    ("HERALDRY", "Coat-of-arms study"),
    ("CHIVALRY", "Knightly code"),
    ("DAMSEL", "Distressed maiden of lore"),
    ("DUNGEON", "Castle's lowest lodging"),
    ("PORTCULLIS", "Castle's iron gate"),
    ("MOAT", "Castle's water barrier"),
    ("RAMPART", "Fortress wall"),
    ("TURRET", "Corner tower"),
    ("GARGOYLE", "Cathedral's stone grotesque"),
    ("CATHEDRAL", "Notre-Dame, for one"),
    ("BASILICA", "St. Peter's, e.g."),
    ("MONASTERY", "Monks' quarters"),
    ("ABBEY", "Westminster ___"),
    ("CLOISTER", "Covered monastic walkway"),
    ("PARCHMENT", "Scribe's writing surface"),
    ("QUILL", "Scribe's pen"),
    ("SCRIBE", "Manuscript copyist"),
    ("ALCHEMY", "Lead-to-gold pursuit"),
    ("APOTHECARY", "Old-time druggist"),
    ("ANTIDOTE", "Poison counter"),
    ("ELIXIR", "Cure-all potion"),
    ("PLACEBO", "Sugar pill"),
    ("VACCINE", "Jenner's smallpox innovation"),
    ("QUARANTINE", "Isolation period"),
    ("EPIDEMIC", "Widespread outbreak"),
    ("ANTIBODY", "Immune system's defender"),
    ("CHROMOSOME", "Gene carrier"),
    ("GENOME", "Full DNA blueprint"),
    ("ENZYME", "Biological catalyst"),
    ("NEURON", "Brain cell"),
    ("SYNAPSE", "Neurons' meeting point"),
    ("CEREBELLUM", "Brain's balance center"),
    ("CRANIUM", "Brain's bone case"),
    ("VERTEBRA", "Spine segment"),
    ("STERNUM", "Breastbone"),
    ("FEMUR", "Body's longest bone"),
    ("TENDON", "Muscle-to-bone tie"),
    ("CARTILAGE", "Nose and ear tissue"),
    ("LIGAMENT", "Bone-to-bone band"),
    ("CAPILLARY", "Tiniest blood vessel"),
    ("AORTA", "Heart's main artery"),
    ("PLASMA", "Blood's liquid part, or a TV type"),
    ("MARROW", "Bone's core"),
    ("METABOLISM", "Body's energy engine"),
    ("PHOTOSYNTHESIS", "How plants make lunch"),
    ("CHLOROPHYLL", "Leaf's green pigment"),
    ("POLLINATION", "Bees' agricultural service"),
    ("GERMINATE", "Sprout from seed"),
    ("PERENNIAL", "Plant that returns yearly"),
    ("DECIDUOUS", "Leaf-dropping, as trees"),
    ("CONIFER", "Cone-bearing tree"),
    ("SEQUOIA", "Giant of the Sierra"),
    ("EUCALYPTUS", "Koala's menu"),
    ("MANGROVE", "Coastal tangle-rooted tree"),
    ("BONSAI", "Tray-sized tree art"),
    ("TOPIARY", "Shrub sculpture"),
    ("ARBORETUM", "Tree museum"),
    ("TERRARIUM", "Glass garden"),
    ("ORCHID", "Fussy exotic bloom"),
    ("WISTERIA", "Cascading purple vine"),
    ("MARIGOLD", "Orange border bloom"),
    ("CHRYSANTHEMUM", "Fall flower with a long name"),
    ("HYDRANGEA", "Bloom that changes color with soil pH"),
    ("LAVENDER", "Purple herb of Provence"),
    ("ROSEMARY", "Herb 'for remembrance'"),
    ("CORIANDER", "Cilantro's seed"),
    ("TURMERIC", "Curry's golden spice"),
    ("SAFFRON", "World's priciest spice"),
    ("PAPRIKA", "Hungarian pepper powder"),
    ("CARDAMOM", "Chai pod spice"),
    ("MOLASSES", "Slow-as-January syrup"),
    ("SOURDOUGH", "Starter-based bread"),
    ("BRIOCHE", "Buttery French bread"),
    ("FOCACCIA", "Dimpled Italian bread"),
    ("PROSCIUTTO", "Paper-thin Italian ham"),
    ("BRUSCHETTA", "Tomato-topped toast"),
    ("MINESTRONE", "Hearty Italian soup"),
    ("GAZPACHO", "Chilled Spanish soup"),
    ("BOUILLABAISSE", "Marseille fish stew"),
    ("RATATOUILLE", "Provençal vegetable stew, or a Pixar rat"),
    ("QUICHE", "Savory custard tart"),
    ("SOUFFLE", "Dish that mustn't fall"),
    ("CREPE", "Paper-thin French pancake"),
    ("CROISSANT", "Crescent of the boulangerie"),
    ("BAGUETTE", "Parisian loaf"),
    ("MACARON", "Delicate French sandwich cookie"),
    ("TIRAMISU", "'Pick-me-up' Italian dessert"),
    ("CANNOLI", "Sicilian cream tube"),
    ("GELATO", "Italy's denser ice cream"),
    ("SORBET", "Dairy-free scoop"),
    ("MERINGUE", "Whipped-white topping"),
    ("CUSTARD", "Crème brûlée base"),
    ("PRALINE", "New Orleans pecan candy"),
    ("BEIGNET", "New Orleans powdered pastry"),
    ("JAMBALAYA", "Louisiana rice jumble"),
    ("GUMBO", "Roux-based Louisiana stew"),
    ("ETOUFFEE", "Crawfish smother"),
    ("CAJUN", "Louisiana cooking style"),
    ("CREOLE", "New Orleans cuisine kin"),
    ("TABASCO", "Louisiana hot sauce"),
    ("CHICORY", "New Orleans coffee additive"),
    ("MARDI", "Fat Tuesday's first word"),
    ("GRAS", "Fat Tuesday's second word"),
    ("ZYDECO", "Louisiana accordion music"),
    ("BAYOU", "Slow Louisiana waterway"),
    ("EVERGLADES", "Florida's river of grass"),
    ("MANATEE", "Florida's gentle sea cow"),
    ("PELICAN", "Pouch-billed diver"),
    ("EGRET", "Elegant white wader"),
    ("HERON", "Patient marsh stalker"),
    ("OSPREY", "Fish-hawk"),
    ("PEREGRINE", "Falcon that dives at 240 mph"),
    ("ALBATROSS", "Sailor's burden, in verse"),
    ("CORMORANT", "Diving coastal bird"),
    ("PUFFIN", "Clown-billed seabird"),
    ("PENGUIN", "Antarctic waddler"),
    ("NARWHAL", "Tusked Arctic whale"),
    ("BELUGA", "White whale, or fancy caviar"),
    ("ORCA", "So-called killer whale"),
    ("HUMPBACK", "Breaching, singing whale"),
    ("PLANKTON", "Whale food, or a Bikini Bottom villain"),
    ("BARNACLE", "Hull hitchhiker"),
    ("ANEMONE", "Clownfish's host"),
    ("CORAL", "Reef builder"),
    ("URCHIN", "Spiny tide-pool ball"),
    ("CUTTLEFISH", "Color-changing cephalopod"),
    ("STINGRAY", "Flat glider with a barbed tail"),
    ("HAMMERHEAD", "Shark with wide-set eyes"),
    ("PIRANHA", "Amazon's toothy fish"),
    ("ANACONDA", "Amazon's giant squeezer"),
    ("CAPYBARA", "World's largest rodent"),
    ("SLOTH", "Slowest mammal, or a deadly sin"),
    ("TOUCAN", "Froot Loops bird"),
    ("MACAW", "Loud rainbow parrot"),
    ("IGUANA", "Sunbathing lizard"),
    ("CHAMELEON", "Reptilian quick-change artist"),
    ("KOMODO", "Dragon of Indonesia"),
    ("GAZELLE", "Cheetah's fleet prey"),
    ("WILDEBEEST", "Great-migration grazer"),
    ("MONGOOSE", "Cobra's nimble nemesis"),
    ("HYENA", "Serengeti scavenger with a 'laugh'"),
    ("JACKAL", "Desert canine of Egypt's Anubis"),
    ("OCELOT", "Small spotted wildcat"),
    ("LYNX", "Tuft-eared wildcat"),
    ("WOLVERINE", "Fierce weasel, or an X-Man"),
    ("ARMADILLO", "Texas roadside armor-bearer"),
    ("PORCUPINE", "Quill-covered rodent"),
    ("OPOSSUM", "It plays dead convincingly"),
    ("MARSUPIAL", "Kangaroo or koala, classwise"),
    ("WALLABY", "Kangaroo's smaller cousin"),
    ("PLATYPUS", "Mammal that lays eggs"),
    ("ECHIDNA", "Spiny egg-laying mammal"),
    ("KOOKABURRA", "Laughing Aussie bird"),
    ("DINGO", "Australia's wild dog"),
    ("OUTBACK", "Australia's vast interior"),
    ("BOOMERANG", "Throw that returns"),
    ("DIDGERIDOO", "Droning Aboriginal instrument"),
    ("TASMANIA", "Devil's island state"),
    ("KIWI", "New Zealander, bird or fruit"),
    ("FIORDLAND", "placeholder-skip"),
    ("HHIMALAYA", "placeholder-skip"),
    ("KATMANDU", "placeholder-skip"),
    ("SHANGHAI", "China's largest city"),
    ("BEIJING", "Forbidden City's home"),
    ("KYOTO", "Japan's temple-filled old capital"),
    ("OSAKA", "Japan's kitchen city"),
    ("SEOUL", "Korea's Han River capital"),
    ("BANGKOK", "Thailand's capital"),
    ("JAKARTA", "Indonesia's crowded capital"),
    ("MUMBAI", "Bollywood's home"),
    ("ISTANBUL", "City on two continents"),
    ("BOSPORUS", "Istanbul's strait"),
    ("CAIRO", "City near Giza"),
    ("MARRAKESH", "Morocco's red city"),
    ("TIMBUKTU", "Byword for the middle of nowhere"),
    ("SERENGETI", "Great migration's plain"),
    ("KILIMANJARO", "Africa's highest peak"),
    ("ZANZIBAR", "Spice island off Tanzania"),
    ("MADAGASCAR", "Lemur's island home"),
    ("GIBRALTAR", "Rock at Spain's tip"),
    ("SANTORINI", "Blue-domed Greek isle"),
    ("REYKJAVIK", "World's northernmost capital"),
    ("HELSINKI", "Finland's capital"),
    ("STOCKHOLM", "Nobel ceremony city (mostly)"),
    ("COPENHAGEN", "Little Mermaid's harbor city"),
    ("AMSTERDAM", "City of canals and bicycles"),
    ("BRUSSELS", "EU headquarters city"),
    ("GENEVA", "Swiss city of conventions"),
    ("MATTERHORN", "Toblerone's mountain"),
    ("EDELWEISS", "Alpine bloom of song"),
    ("YODEL", "Alpine vocal echo"),
    ("FONDUE", "Communal Swiss pot"),
    ("STRUDEL", "Viennese apple pastry"),
    ("PRETZEL", "Bavarian twist"),
    ("OKTOBERFEST", "Munich's big party"),
    ("AUTOBAHN", "No-limit German highway"),
    ("BRATWURST", "German grill sausage"),
    ("SAUERKRAUT", "Fermented cabbage side"),
    ("GOULASH", "Hungarian paprika stew"),
    ("BORSCHT", "Beet-red soup"),
    ("SAMOVAR", "Russian tea urn"),
    ("BABUSHKA", "Russian grandmother"),
    ("MATRYOSHKA", "Nesting doll"),
    ("KREMLIN", "Moscow's fortress"),
    ("SIBERIA", "Russia's frozen expanse"),
    ("COSSACK", "Steppe horseman"),
    ("TROIKA", "Three-horse sleigh"),
    ("BALALAIKA", "Triangular Russian strummer"),
    ("PIEROGI", "Polish stuffed dumpling"),
    ("PAELLA", "Valencia's saffron rice"),
    ("SANGRIA", "Spanish wine punch"),
    ("TAPAS", "Small Spanish plates"),
    ("CHURRO", "Ridged fried dough stick"),
    ("EMPANADA", "Latin turnover"),
    ("CEVICHE", "Citrus-cured seafood"),
    ("QUINOA", "Andean super-grain"),
    ("LLAMA", "Andean pack animal"),
    ("ALPACA", "Llama's woollier cousin"),
    ("CONDOR", "Andes' huge glider"),
    ("PATAGONIA", "South America's wild south"),
    ("GALAPAGOS", "Darwin's finch islands"),
    ("AMAZONIA", "placeholder-skip"),
    ("CARNIVAL", "Rio's pre-Lent blowout"),
    ("IPANEMA", "Rio beach of song"),
    ("BOSSA", "___ nova"),
    ("TANGO", "Buenos Aires dance"),
    ("GAUCHO", "Pampas cowboy"),
    ("PAMPAS", "Argentine grasslands"),
    ("YUCATAN", "Peninsula of Chichén Itzá"),
    ("AZTEC", "Montezuma's people"),
    ("MAYA", "Builders of Tikal"),
    ("INCA", "Machu Picchu builders"),
    ("QUETZAL", "Resplendent Central American bird"),
    ("SOMBRERO", "Wide-brimmed hat"),
    ("MARIACHI", "Strolling Mexican band"),
    ("PINATA", "Blindfolded batter's target"),
    ("SIESTA", "Afternoon rest"),
    ("FIESTA", "Spanish celebration"),
    ("HACIENDA", "Spanish estate"),
    ("ADOBE", "Sun-dried brick"),
    ("PUEBLO", "Southwest cliff village"),
    ("KACHINA", "Hopi spirit doll"),
    ("TOTEM", "Carved Pacific Northwest pole"),
    ("IGLOO", "Snow-block dome"),
    ("KAYAK", "Inuit invention that reads both ways"),
    ("HUSKY", "Iditarod runner"),
    ("IDITAROD", "Alaskan sled race"),
    ("KLONDIKE", "1890s gold rush region"),
    ("AURORA", "Northern lights, formally"),
    ("MERIDIAN", "Longitude line"),
    ("SEXTANT", "Navigator's angle-measurer"),
    ("ASTROLABE", "Ancient star-sighting tool"),
    ("CARTOGRAPHER", "Map maker"),
    ("TOPOGRAPHY", "Lay of the land"),
    ("PENINSULA", "Almost-island"),
    ("ISTHMUS", "Panama's land link"),
    ("STRAIT", "Narrow sea passage"),
    ("ATOLL", "Ring-shaped reef isle"),
    ("LAGOON", "Atoll's calm center"),
    ("ESTUARY", "Where river meets tide"),
    ("TRIBUTARY", "River feeder"),
    ("CONFLUENCE", "Rivers' meeting point"),
    ("WATERSHED", "Drainage basin, or a turning point"),
    ("RESERVOIR", "Dammed water supply"),
    ("IRRIGATION", "Farm watering system"),
    ("WINDMILL", "Don Quixote's 'giant'"),
    ("SILO", "Grain tower"),
    ("THRESHER", "Grain separator, or a shark"),
    ("SCYTHE", "Grim Reaper's tool"),
    ("SICKLE", "Curved harvest blade"),
    ("PLOWSHARE", "What swords become, in Isaiah"),
    ("FALLOW", "Resting, as a field"),
    ("VINEYARD", "Napa parcel"),
    ("SOMMELIER", "Wine steward"),
    ("DECANTER", "Wine-breathing vessel"),
    ("BORDEAUX", "French wine region"),
    ("CHIANTI", "Tuscan red"),
    ("PROSECCO", "Italy's bubbly"),
    ("VERMOUTH", "Martini's other ingredient"),
    ("BITTERS", "Old-fashioned dashes"),
    ("MIXOLOGY", "Craft of the cocktail"),
    ("SPEAKEASY", "Prohibition-era bar"),
    ("BOOTLEG", "Smuggle, Prohibition-style"),
    ("MOONSHINE", "Backwoods white lightning"),
    ("JUKEBOX", "Diner's coin-fed DJ"),
    ("VAUDEVILLE", "Variety stage of yore"),
    ("BURLESQUE", "Theatrical send-up"),
    ("RAGTIME", "Joplin's genre"),
    ("CHARLESTON", "1920s dance craze, or a Carolina city"),
    ("FLAPPER", "Jazz Age fashionista"),
    ("GATSBY", "Fitzgerald's great one"),
    ("PULITZER", "Journalism's big prize"),
    ("NEWSREEL", "Pre-feature footage of old"),
    ("TELETHON", "Marathon fundraiser broadcast"),
    ("SYNDICATE", "Sell to many papers at once"),
    ("TABLOID", "Checkout-line paper"),
    ("PAPARAZZI", "Celebrity chasers"),
    ("MATINEE2", "placeholder-skip"),
    ("CELLULOID", "Old film stock"),
    ("TECHNICOLOR", "Oz's vivid process"),
    ("STORYBOARD", "Film's comic-strip plan"),
    ("SCREENPLAY", "Film's blueprint"),
    ("BLOCKBUSTER", "Summer smash"),
    ("CLIFFHANGER", "Serial's suspenseful end"),
    ("FLASHBACK", "Scene from the past"),
    ("VOICEOVER", "Unseen narration"),
    ("STUNTMAN", "Star's daring double"),
    ("PYROTECHNICS", "Movie set fireworks"),
    ("ANIMATRONIC", "Disney robot figure"),
    ("MARIONETTE", "Stringed puppet"),
    ("VENTRILOQUIST", "One who throws a voice"),
    ("ILLUSIONIST", "Stage magician"),
    ("HOUDINI", "Escape artist of legend"),
    ("SLEIGHT", "___ of hand"),
    ("ABRACADABRA", "Magic word"),
    ("TAROT", "Fortune-teller's deck"),
    ("OUIJA", "Séance board"),
    ("CLAIRVOYANT", "Alleged future-seer"),
    ("TELEPATHY", "Mind-to-mind link"),
    ("POLTERGEIST", "Noisy ghost"),
    ("APPARITION", "Ghostly appearance"),
    ("SEANCE", "Table-tapping session"),
    ("MAUSOLEUM", "Grand tomb"),
    ("OBITUARY", "Life summary in the paper"),
    ("EULOGY", "Funeral tribute"),
    ("EPITAPH", "Headstone words"),
    ("REQUIEM", "Mass for the dead"),
    ("PURGATORY", "Dante's middle realm"),
    ("INFERNO", "Dante's first realm"),
    ("LIMERICK", "Five-line nonsense verse"),
    ("SONNET", "Shakespeare wrote 154"),
    ("HAIKU", "Poem of 5-7-5"),
    ("STANZA", "Poem's paragraph"),
    ("COUPLET", "Rhymed pair of lines"),
    ("IAMBIC", "Like Shakespeare's pentameter"),
    ("BALLAD", "Storytelling song"),
    ("TROUBADOUR", "Medieval singing poet"),
    ("MINSTREL", "Wandering medieval musician"),
    ("BARD", "Shakespeare, with 'the'"),
    ("FOLIO", "Shakespeare's first collection"),
    ("OTHELLO", "Moor of Venice"),
    ("MACBETH", "Scottish play title role"),
    ("HAMLET", "Melancholy Dane"),
    ("OPHELIA", "Hamlet's doomed love"),
    ("FALSTAFF", "Shakespeare's fat knight"),
    ("PROSPERO", "Tempest's magician"),
    ("CALIBAN", "Tempest's brute"),
    ("VERONA", "Romeo and Juliet's city"),
    ("ELSINORE", "Hamlet's castle"),
    ("SOOTHSAYER", "'Beware the ides' speaker"),
    ("RUBICON", "River Caesar famously crossed"),
    ("SENATE2", "placeholder-skip"),
    ("TOGA", "Roman wrap"),
    ("CENTURION", "Roman officer of 100"),
    ("LEGION", "Rome's army unit"),
    ("VESUVIUS", "Pompeii's destroyer"),
    ("POMPEII", "City frozen in ash"),
    ("PANTHEON", "Rome's domed temple to all gods"),
    ("FORUM", "Rome's public square"),
    ("CHARIOT", "Ben-Hur's ride"),
    ("OBELISK", "Pointed stone pillar"),
    ("PAPYRUS", "Nile-reed paper"),
    ("ROSETTA", "Stone that cracked hieroglyphs"),
    ("NEFERTITI", "Famously sculpted Egyptian queen"),
    ("TUTANKHAMUN", "Boy king of the golden mask"),
    ("SCARAB", "Sacred Egyptian beetle"),
    ("ANUBIS", "Jackal-headed god"),
    ("PHARAOH", "Nile throne holder"),
    ("DYNASTY", "Ruling family line"),
    ("CLEOPATRA", "Last pharaoh of Egypt"),
    ("BABYLON", "Hanging Gardens city"),
    ("ZIGGURAT", "Mesopotamian stepped tower"),
    ("CUNEIFORM", "Wedge-shaped writing"),
    ("MESOPOTAMIA", "Land between the rivers"),
    ("EUPHRATES", "Tigris' twin river"),
    ("SAHARA", "World's largest hot desert"),
    ("BEDOUIN", "Desert nomad"),
    ("CARAVAN", "Camel convoy"),
    ("MINARET", "Mosque's tower"),
    ("BAZAAR", "Middle Eastern market"),
    ("SULTAN", "Ottoman ruler"),
    ("SCHEHERAZADE", "Teller of 1,001 tales"),
    ("ALADDIN", "Lamp-rubbing tale hero"),
    ("SINBAD", "Sailor of seven voyages"),
    ("MAGICCARPET", "placeholder-skip"),
    ("TURBAN", "Wound headwear"),
    ("MONSOON2", "placeholder-skip"),
    ("RICKSHAW", "Human-powered taxi"),
    ("PAGODA", "Tiered temple tower"),
    ("ORIGAMI", "Paper crane art"),
    ("HAIKU2", "placeholder-skip"),
    ("BONSAI2", "placeholder-skip"),
    ("SAMURAI", "Katana carrier"),
    ("SHOGUN", "Japan's military ruler of old"),
    ("NINJA", "Shadow-cloaked agent"),
    ("KIMONO", "Wrapped Japanese robe"),
    ("SUMO", "Wrestling of giants"),
    ("KABUKI", "Stylized Japanese theater"),
    ("TSUNAMI", "Harbor wave"),
    ("TATAMI", "Japanese floor mat"),
    ("WASABI", "Sushi's green fire"),
    ("TEMPURA", "Light Japanese batter-fry"),
    ("TERIYAKI", "Sweet soy glaze"),
    ("EDAMAME", "Salted soybean starter"),
    ("SRIRACHA", "Rooster-bottle hot sauce"),
    ("KIMCHI", "Korea's fermented staple"),
    ("DIMSUM", "placeholder-skip"),
    ("WONTON", "Chinese dumpling in soup"),
    ("SZECHUAN", "Numbing-spicy Chinese cuisine"),
    ("MANDARIN", "China's main tongue, or a small orange"),
    ("DDRAGON", "placeholder-skip"),
    ("TYPHOON2", "placeholder-skip"),
    ("TERRACOTTA", "Xi'an's army material"),
    ("PORCELAIN", "Fine china"),
    ("JADE", "Prized green stone"),
    ("SILKROAD", "placeholder-skip"),
    ("ABACUS", "Bead-based calculator"),
    ("ALGORITHM", "Step-by-step procedure"),
    ("QUADRATIC", "Kind of equation with x-squared"),
    ("FIBONACCI", "1, 1, 2, 3, 5, 8 man"),
    ("GEOMETRY", "Euclid's field"),
    ("PYTHAGORAS", "Right-triangle theorem man"),
    ("CALCULUS", "Newton and Leibniz's invention"),
    ("INFINITY", "Sideways-eight concept"),
    ("FRACTAL", "Endlessly self-similar pattern"),
    ("PENDULUM", "Foucault's swinger"),
    ("FULCRUM", "Lever's pivot"),
    ("MOMENTUM", "Mass times velocity"),
    ("FRICTION", "Motion's rub"),
    ("INERTIA", "Newton's first-law property"),
    ("CENTRIFUGE", "Lab spinner"),
    ("CRUCIBLE", "Melting pot, or a Miller play"),
    ("LITMUS", "Acid test paper"),
    ("CATALYST", "Reaction speeder"),
    ("ISOTOPE", "Atomic variant"),
    ("MOLECULE", "H2O, e.g."),
    ("ELECTRON", "Negative particle"),
    ("PHOTON", "Light particle"),
    ("QUARK", "Subatomic building block"),
    ("PLUTONIUM", "Element 94"),
    ("TITANIUM", "Strong, light metal"),
    ("TUNGSTEN", "Old bulb filament metal"),
    ("GRAPHITE", "Pencil 'lead'"),
    ("OBSIDIAN", "Volcanic glass"),
    ("AMETHYST", "Purple quartz"),
    ("TURQUOISE", "Southwest's blue-green stone"),
    ("SAPPHIRE", "September's blue stone"),
    ("MOTHERLODE", "Miner's jackpot"),
    ("EXCAVATION", "Dig site work"),
    ("ARTIFACT", "Dig site find"),
    ("CARBON2", "placeholder-skip"),
    ("PALEONTOLOGY", "Dinosaur science"),
    ("VELOCIRAPTOR", "Swift Cretaceous hunter"),
    ("PTERODACTYL", "Winged reptile, loosely"),
    ("STEGOSAURUS", "Plated, spike-tailed dino"),
    ("TRICERATOPS", "Three-horned dino"),
    ("MAMMOTH", "Woolly Ice Age giant"),
    ("NEANDERTHAL", "Ice Age human cousin"),
    ("GLACIER", "Ice river"),
    ("ICEBERG", "Titanic's undoing"),
    ("ANTARCTICA", "Coldest continent"),
    ("EXPANSE", "placeholder-skip"),
    ("LATITUDE", "Equator's measure"),
    ("LONGITUDE", "Greenwich's measure"),
    ("CHRONOMETER", "Sea clock that solved longitude"),
    ("HOURGLASS", "Sand timer"),
    ("SUNDIAL", "Shadow clock"),
    ("METRONOME", "Pianist's tick-tock"),
    ("ALMANAC", "Farmer's yearly reference"),
    ("GAZETTEER", "Geographic index"),
    ("ATLAS2", "placeholder-skip"),
    ("MERCATOR", "Map projection name"),
    ("ORIENTEERING", "Map-and-compass sport"),
    ("SPELUNKING", "Cave exploring"),
    ("RAPPELLING", "Rope descent"),
    ("PARKOUR", "Urban vaulting discipline"),
    ("SLACKLINE", "Modern tightrope"),
    ("BIATHLON", "Ski-and-shoot event"),
    ("DECATHLON", "Ten-event test"),
    ("PENTATHLON", "Five-event contest"),
    ("STEEPLECHASE", "Track race with water jumps"),
    ("VELODROME", "Banked cycling oval"),
    ("PELOTON", "Cycling's main pack"),
    ("REGATTA", "Rowing meet"),
    ("COXSWAIN", "Rowing crew's caller"),
    ("SPINNAKER", "Billowing racing sail"),
    ("SLALOM", "Gate-weaving ski event"),
    ("MOGUL", "Ski bump, or a tycoon"),
    ("HALFPIPE", "Snowboarder's U"),
    ("LUGE", "Feet-first ice sled"),
    ("SKELETON", "Head-first ice sled, or what's in the closet"),
    ("CURLING", "Sport with brooms and stones"),
    ("ZAMBONI", "Ice resurfacer"),
    ("HATTRICK", "placeholder-skip"),
    ("SHUTOUT", "Zero for the visitors"),
    ("SOUTHPAW", "Lefty pitcher"),
    ("KNUCKLEBALL", "Fluttering pitch"),
    ("BULLPEN", "Relievers' waiting area"),
    ("DUGOUT", "Bench by the diamond"),
    ("GRANDSLAM", "placeholder-skip"),
    ("PENNANT", "League championship flag"),
    ("HEISMAN", "College football's top trophy"),
    ("GRIDIRON", "Football field"),
    ("SCRIMMAGE", "Line of ___"),
    ("AUDIBLE", "QB's line-of-scrimmage change"),
    ("BLITZ", "All-out pass rush"),
    ("ONSIDE", "Risky kind of kick"),
    ("FUMBLE", "Ball-carrier's blunder"),
    ("TAILGATE", "Parking lot pregame"),
    ("VUVUZELA", "Droning World Cup horn"),
    ("NUTMEG", "Through-the-legs soccer move, or a spice"),
    ("BICYCLE", "Overhead soccer kick, or a two-wheeler"),
    ("DRIBBLE", "Advance the ball, in two sports"),
    ("ALLEYOOP", "placeholder-skip"),
    ("BUZZERBEATER", "placeholder-skip"),
    ("BACKBOARD", "Rim's backdrop"),
    ("FREETHROW", "placeholder-skip"),
    ("TIPOFF", "Basketball's start"),
    ("DEUCE", "40-40, in tennis"),
    ("TIEBREAK", "Set decider"),
    ("TOPSPIN", "Forward-rotating shot"),
    ("BACKHAND", "Two-handed stroke, often"),
    ("WIMBLEDON", "Grass-court grand slam"),
    ("FOREHAND", "Tennis player's bread and butter"),
    ("VOLLEY", "Shot before the bounce"),
    ("BbACKSPIN", "placeholder-skip"),
    ("ALBATROSS2", "placeholder-skip"),
    ("SANDBAGGER", "Golfer hiding his true skill"),
    ("MULLIGAN", "Golfer's do-over"),
    ("FAIRWAY", "Between tee and green"),
    ("GALLERY", "Golf tournament crowd, or an art hall"),
    ("SCORECARD", "Round's record"),
    ("HANDICAP", "Golfer's equalizer"),
    ("LINKSLAND", "placeholder-skip"),
    ("CLUBHOUSE", "19th-hole hangout"),
]


def clean_bank(bank):
    seen = set()
    out = []
    for w, clue in bank:
        if "placeholder" in clue.lower():
            continue
        if not w.isalpha() or not w.isupper() or w != w.upper():
            continue
        if w in seen:
            continue
        seen.add(w)
        out.append((w, clue))
    return out


# ---------------------------------------------------------------------------
# Freeform (criss-cross) builder: words interlock; every crossing letter is
# shared; unfilled cells are blocks. Same construction style as newspaper
# "criss-cross" puzzles, sized 15x15 (easy) and 21x21 (medium).
# ---------------------------------------------------------------------------
class Builder:
    def __init__(self, size, rng):
        self.size = size
        self.rng = rng
        self.grid = [[None] * size for _ in range(size)]
        self.placed = []

    def cell(self, r, c):
        if 0 <= r < self.size and 0 <= c < self.size:
            return self.grid[r][c]
        return None

    def placements_for(self, word):
        """All legal placements crossing an existing word, with crossing counts."""
        opts = []
        for pw, pr, pc, ph in self.placed:
            pdr, pdc = (0, 1) if ph else (1, 0)
            for j, pch in enumerate(pw):
                cr, cc = pr + pdr * j, pc + pdc * j
                for i, ch in enumerate(word):
                    if ch != pch:
                        continue
                    if ph:
                        nr, nc, nh = cr - i, cc, False
                    else:
                        nr, nc, nh = cr, cc - i, True
                    k = self.crossings_if_ok(word, nr, nc, nh)
                    if k:
                        opts.append((nr, nc, nh, k))
        return opts

    def crossings_if_ok(self, word, r, c, horiz):
        n = len(word)
        dr, dc = (0, 1) if horiz else (1, 0)
        er, ec = r + dr * (n - 1), c + dc * (n - 1)
        if r < 0 or c < 0 or er >= self.size or ec >= self.size:
            return 0
        if self.cell(r - dr, c - dc) is not None or self.cell(er + dr, ec + dc) is not None:
            return 0
        crossings = 0
        for i, ch in enumerate(word):
            rr, cc = r + dr * i, c + dc * i
            cur = self.grid[rr][cc]
            if cur is not None:
                if cur != ch:
                    return 0
                crossings += 1
            else:
                if horiz:
                    if self.cell(rr - 1, cc) is not None or self.cell(rr + 1, cc) is not None:
                        return 0
                else:
                    if self.cell(rr, cc - 1) is not None or self.cell(rr, cc + 1) is not None:
                        return 0
        return crossings

    def place(self, word, r, c, horiz):
        dr, dc = (0, 1) if horiz else (1, 0)
        for i, ch in enumerate(word):
            self.grid[r + dr * i][c + dc * i] = ch
        self.placed.append((word, r, c, horiz))

    def try_add(self, word):
        opts = self.placements_for(word)
        if not opts:
            return False
        # favor placements with more crossings — denser, more interlocked grids
        weights = [k * k for (_, _, _, k) in opts]
        r, c, h, _ = self.rng.choices(opts, weights=weights, k=1)[0]
        self.place(word, r, c, h)
        return True


def build_candidate(bank, size, max_words, rng):
    words = bank[:]
    rng.shuffle(words)
    b = Builder(size, rng)
    long_pool = [w for w in words if len(w[0]) >= size // 2][:40] or words[:40]
    seed = rng.choice(long_pool)
    b.place(seed[0], size // 2, (size - len(seed[0])) // 2, True)
    used = {seed[0]: seed[1]}
    for _ in range(4):
        if len(b.placed) >= max_words:
            break
        for w, clue in words:
            if w in used or len(w) > size:
                continue
            if b.try_add(w):
                used[w] = clue
                if len(b.placed) >= max_words:
                    break
    return b, used


def build_puzzle(bank, size, min_words, max_words, rng, tries=4):
    best = None
    for _ in range(tries):
        b, used = build_candidate(bank, size, max_words, rng)
        if best is None or len(b.placed) > len(best[0].placed):
            best = (b, used)
        if len(best[0].placed) >= max_words:
            break
    b, used = best
    if len(b.placed) < min_words:
        return None
    return finalize(b, used)


def finalize(b, used):
    # keep the full fixed grid size; just center the fill within it
    rows = [r for r in range(b.size) for c in range(b.size) if b.grid[r][c]]
    cols = [c for r in range(b.size) for c in range(b.size) if b.grid[r][c]]
    r0, r1, c0, c1 = min(rows), max(rows), min(cols), max(cols)
    h, w = r1 - r0 + 1, c1 - c0 + 1
    size = b.size
    off_r, off_c = (size - h) // 2 - r0, (size - w) // 2 - c0
    grid = [[None] * size for _ in range(size)]
    for r in range(b.size):
        for c in range(b.size):
            if b.grid[r][c]:
                grid[r + off_r][c + off_c] = b.grid[r][c]

    def starts(r, c, dr, dc):
        if grid[r][c] is None:
            return False
        pr, pc = r - dr, c - dc
        nr, nc = r + dr, c + dc
        prev = grid[pr][pc] if 0 <= pr < size and 0 <= pc < size else None
        nxt = grid[nr][nc] if 0 <= nr < size and 0 <= nc < size else None
        return prev is None and nxt is not None

    across, down = [], []
    num = 0
    for r in range(size):
        for c in range(size):
            sa, sd = starts(r, c, 0, 1), starts(r, c, 1, 0)
            if not (sa or sd):
                continue
            num += 1
            if sa:
                word = ""
                cc = c
                while cc < size and grid[r][cc] is not None:
                    word += grid[r][cc]
                    cc += 1
                across.append([num, r, c, len(word), used[word]])
            if sd:
                word = ""
                rr = r
                while rr < size and grid[rr][c] is not None:
                    word += grid[rr][c]
                    rr += 1
                down.append([num, r, c, len(word), used[word]])

    g = ["".join(ch if ch else "." for ch in row) for row in grid]
    return {"s": size, "g": g, "a": across, "d": down, "sig": frozenset(used)}


def verify(p, expect_max_size):
    size, g = p["s"], p["g"]
    assert size == expect_max_size, "wrong grid size"
    cells = {(r, c) for r in range(size) for c in range(size) if g[r][c] != "."}
    assert cells, "empty grid"
    stack = [next(iter(cells))]
    seen = set(stack)
    while stack:
        r, c = stack.pop()
        for nr, nc in ((r + 1, c), (r - 1, c), (r, c + 1), (r, c - 1)):
            if (nr, nc) in cells and (nr, nc) not in seen:
                seen.add((nr, nc))
                stack.append((nr, nc))
    assert seen == cells, "grid not connected"
    for lst, horiz in ((p["a"], True), (p["d"], False)):
        for num, r, c, ln, clue in lst:
            assert ln >= 2 and clue
            for i in range(ln):
                rr, cc = (r, c + i) if horiz else (r + i, c)
                assert g[rr][cc] != "."


def make_set(bank, count, size, min_words, max_words, seed):
    rng = random.Random(seed)
    puzzles, sigs = [], set()
    attempts = 0
    while len(puzzles) < count:
        attempts += 1
        if attempts > count * 200:
            raise RuntimeError("could not generate enough distinct puzzles")
        p = build_puzzle(bank, size, min_words, max_words, rng)
        if p is None or p["sig"] in sigs:
            continue
        verify(p, size)
        sigs.add(p["sig"])
        del p["sig"]
        puzzles.append(p)
    return puzzles


def main():
    easy_bank = clean_bank(EASY)
    medium_bank = clean_bank(MEDIUM)
    print(f"banks: easy={len(easy_bank)} words, medium={len(medium_bank)} words")
    easy = make_set(easy_bank, 100, size=15, min_words=20, max_words=26, seed=1509)
    medium = make_set(medium_bank, 100, size=21, min_words=28, max_words=36, seed=2109)
    data = {"easy": easy, "medium": medium}
    out = "window.PUZZLES=" + json.dumps(data, separators=(",", ":")) + ";\n"
    path = sys.argv[1] if len(sys.argv) > 1 else "puzzles.js"
    with open(path, "w") as f:
        f.write(out)
    for name, ps in (("easy", easy), ("medium", medium)):
        avg = sum(len(p["a"]) + len(p["d"]) for p in ps) / len(ps)
        sizes = sorted({p["s"] for p in ps})
        print(f"{name}: {len(ps)} puzzles, avg {avg:.1f} entries, sizes {sizes}")
    print(f"wrote {path} ({len(out):,} bytes)")


if __name__ == "__main__":
    main()
